architectury {
    common(project.enabled_platforms.split(","))
}

dependencies {
    modImplementation "dev.architectury:architectury:${project.architectury_version}"

    modCompileOnly "fuzs.forgeconfigapiport:forgeconfigapiport-common:${project.forge_config_api_port_version}"
    modCompileOnly "fuzs.forgeconfigapiport:forgeconfigapiport-common-neoforgeapi:${project.forge_config_api_port_version}"

    modCompileOnly "software.bernie.geckolib:geckolib-neoforge-${project.mc_version}:${project.geckolib_version}"

    modCompileOnly "maven.modrinth:terrafirmacraft:${project.tfc_version}"
}
